export { createQueryHelpers, POSTS_PER_PAGE } from './queries/createQueryHelpers'
export type { QueryHelpers } from './queries/createQueryHelpers'
export { withAiRoute, withAiRouteSimple } from './route-handler'
export { createSitemap } from './sitemap'
export { createRobots } from './robots'
export { createPostsHandler } from './routes/posts/createPostsHandler'

// Re-export AI route handlers for thin app wrappers
export { POST as generateTitlePOST } from './routes/generate-title/route'
export { POST as generateOutlinePOST } from './routes/generate-outline/route'
export { POST as generateMetaTitlePOST } from './routes/generate-meta-title/route'
export { POST as generateMetaDescriptionPOST } from './routes/generate-meta-description/route'
export { POST as generateMetaPOST } from './routes/generate-meta/route'
export { POST as generateSlugPOST } from './routes/generate-slug/route'
export { POST as generateFaqPOST } from './routes/generate-faq/route'
export { POST as generateExcerptPOST } from './routes/generate-excerpt/route'
export { POST as generateAltTextPOST } from './routes/generate-alt-text/route'
export { POST as generateSocialPOST } from './routes/generate-social/route'
export { POST as generateSocialCaptionsPOST } from './routes/generate-social-captions/route'
export { POST as generateContentBriefPOST } from './routes/generate-content-brief/route'
export { POST as detectSearchIntentPOST } from './routes/detect-search-intent/route'
export { POST as generateCtaPOST } from './routes/generate-cta/route'
export { POST as improveReadabilityPOST } from './routes/improve-readability/route'
export { POST as seoScorePOST } from './routes/seo-score/route'
export { GET as providerInfoGET } from './routes/provider-info/route'
